sudo: required
services:
  - dockerfile

before_install:
  - docker build -t robertotesta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robertotesta/docker-react npm run test