sudo: required
services:
  - dockerfile

before_install:
  - docker build -t robertotesta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robertotesta/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-221422314408"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"